.base-image-build:
  tags:
    - ubuntu
  image: ubuntu:latest
  extends:
    - .default
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN


build-images:develop:
  extends:
    - .base-image-build
    - .filter:rules:push-develop-branch
  stage: build
  script:
    - docker build -t $DOCKER_REPOSITORY:develop ./server/
    - docker push $DOCKER_REPOSITORY:develop

build-images:latest:
  extends:
    - .base-image-build
    - .filter:rules:push-production-branch
  stage: build
  script:
    - docker build -t $DOCKER_REPOSITORY:latest ./server/
    - docker push $DOCKER_REPOSITORY:latest