#####################
# Deploy on GCP Run #
#####################

.deploy-gcp:
  image: google/cloud-sdk
  services:
    - docker:dind
  extends:
    - .auth-gcp
  stage: deploy
  tags:
    - dind
  script:
    - gcloud run deploy $GCP_SERVICE_NAME-$TYPE_PROJECT --project $GCP_PROJECT_ID --region $GCP_REGION --image $GCP_IMAGE --platform managed


deploy:production-gcp:
  needs: ["build:gcp"]
  extends:
    - .filter:rules:push-production-branch
    - .deploy-gcp
  variables:
    TYPE_PROJECT: "production"

deploy:sandbox-gcp:
  needs: ["build:gcp"]
  extends:
    - .filter:rules:push-develop-branch
    - .deploy-gcp
  variables:
    TYPE_PROJECT: "sandbox"
